config/routes.rb
Art::Application.routes.draw do
  devise_for :admins
  root to: 'welcome#index'

  resources :paintings, only: [:index, :show]

  namespace :admin do
    resources :paintings
    resources :feedbacks
    resources :posts
    resources :authors
  end

  get 'tags/:tag', to: 'paintings#index', as: :tag
  get '/about', to: 'welcome#about'

  resources :feedbacks, only: [:new, :create]
  resources :posts, only: [:show, :index]
  resources :authors, only: [:show]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :description, :name, :avatar
  has_many :paintings, dependent: :destroy

  mount_uploader :avatar, AvatarUploader
  validates_presence_of :avatar
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :email, :message, :name, :phone
  validates_presence_of :email, :name, :message
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :description, :name, :pub_year, :image, :tag_list, :author_id
  mount_uploader :image, ImageUploader
  acts_as_taggable
  validates_presence_of :name, :image, :description, :author_id
  belongs_to :author

  delegate :name, to: :author, prefix: true, allow_nil: true

  def related_paintings(count=5)
    Painting.where(:author_id => self.author_id).sample(count)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
  validates_presence_of :title, :content
end

app/controllers/admin/authors_controller.rb
#encoding: utf-8
class Admin::AuthorsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin!

  def index
    @authors = Author.paginate(page: params[:page])
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(params[:author])
    if @author.save
      redirect_to admin_author_path(@author), notice: '作家新增成功'
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(params[:author])
      redirect_to admin_author_path(@author), notice: '作者更新成功'
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to admin_authors_path, notice: '作者刪除成功'
  end

end

app/controllers/admin/feedbacks_controller.rb
class Admin::FeedbacksController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin!

  def index
    @feedbacks = Feedback.paginate(page: params[:page])
  end

  def show
    @feedback = Feedback.find(params[:id])
  end

end

app/controllers/admin/paintings_controller.rb
#encoding: utf-8
class Admin::PaintingsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin!

  def index
    @paintings = Painting.paginate(page: params[:page])
  end

  def show
    @painting = Painting.find(params[:id])
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.new(params[:painting])
    if @painting.save
      redirect_to admin_painting_path(@painting), notice: '作品新增成功'
    else
      render :new
    end
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:id])
    if @painting.update_attributes(params[:painting])
      redirect_to admin_painting_path(@painting), notice: '作品更新成功'
    else
      render :edit
    end
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    redirect_to admin_paintings_path, notice: '作品刪除成功'
  end

end

app/controllers/admin/posts_controller.rb
#encoding: utf-8
class Admin::PostsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin!

  def index
    @posts = Post.paginate(page: params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to admin_posts_path, notice: '更新成功'
    else
      render :edit
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to admin_posts_path, notcie: '新增成功'
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: '刪除成功'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def show
    @author = Author.find(params[:id])
  end

end

app/controllers/feedbacks_controller.rb
#encoding: utf-8
class FeedbacksController < ApplicationController

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.create(params[:feedback])
    if @feedback.save
      respond_to do |format|
        format.js
      end
    else
      render :new
    end
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

  def index
    if params[:tag]
      @paintings = Painting.tagged_with(params[:tag]).paginate(page: params[:page])
    else
      @paintings = Painting.paginate(page: params[:page])
    end
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @painting = Painting.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :load_sidebar

  def index
    @posts = Post.paginate(page: params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  protected

  def load_sidebar
    @latest = Post.last(5)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @paintings = Painting.last(5)
  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def footer_authors
    Author.all.sample(15)
  end

  def footer_posts
    Post.last(6)
  end

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      sha = Digest::SHA1.hexdigest(code)
        Rails.cache.fetch ["code", language, sha].join('-') do
          Pygments.highlight(code, lexer:language)
        end
      end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/views/admin/authors/_form.html.slim
= simple_form_for([:admin, @author], html: { class: 'form-horizontal' }) do |f|
  = f.input :name, label: '作家姓名'
  = f.input :avatar, label: '作家頭像', as: :image_preview, input_html: { preview_version: :thumb }
  = f.input :description, label: '作家敘述', input_html: { class: 'span12', rows: 20 }
  .form-actions
    = f.submit '送出', class: 'btn btn-primary btn-large'

app/views/admin/authors/edit.html.slim
.span12
  .well.widget
    .widget-header
      h3.title 編輯作者
    = render 'form'

app/views/admin/authors/index.html.slim
.row-fluid
  .span12
    table.table.table-striped.table-bordered.table-condensed
      thead
        tr
          th 作者
          th 作品數
          th 敘述
          th 建立時間
          th 更新時間
          th 操作
      tbody
        - @authors.each do |author|
          tr
            td= author.name
            td= author.paintings.count
            td= author.description
            td= l author.created_at, format: :long
            td= l author.updated_at, format: :long
            td
              .btn-group
                = link_to edit_admin_author_path(author), :class => 'btn' do
                  = content_tag(:i, '', :class => 'icon icon-edit')
                  '  編輯
                = link_to admin_author_path(author), method: :delete, data: { confirm: '確認要刪除嗎？' }, class: 'btn btn-danger' do
                  = content_tag(:i, '', class: 'icon icon-remove')
                  '  刪除
  = will_paginate @authors

app/views/admin/authors/new.html.slim
.span12
  .well.widget
    .widget-header
      h3.title 新增作者
    = render 'form'

app/views/admin/authors/show.html.slim
.span3
  .well.widget
    .widget-header
    .widget-content
      = image_tag(@author.avatar.url(:normal))
.span9
  .well.widget
    .widget-header
      h3= @author.name
      .widget-nav
        .dropdown.nav-item
          a.dropdown-toggle href="#" data-toggle="dropdown"
            i.icon-cog
          ul.dropdown-menu.pull-right
            li= link_to '編輯', edit_admin_author_path(@author)
    .widget-content
      = markdown @author.description

app/views/admin/feedbacks/index.html.slim
.row-fluid
  .span12
    .well.widget
      .widget-header
        h3 意見清單
      .widget-content
        table.table.table-striped.table-bordered.table-condensed
          thead
            tr
              th 姓名
              th Email
              th 電話
              th 意見
              th 建立時間
          tbody
            - @feedbacks.each do |feedback|
              tr
                td= feedback.name
                td= feedback.email
                td= feedback.phone
                td= feedback.message
                td= l feedback.created_at, format: :long
      = will_paginate @feedbacks

app/views/admin/paintings/_form.html.slim
= simple_form_for([:admin, @painting], html: { class: 'form-horizontal' }) do |f|
  = f.input :name, label: '作品名稱'
  = f.input :image, label: '作品圖片', as: :image_preview, input_html: {preview_version: :thumb}
  = f.association :author, label: '作者', include_blank: false
  = f.input :tag_list, label: '標籤', hint: '用逗號隔開不同標籤'
  = f.input :pub_year, label: '年份', placeholder: '2012 或是 2011-2012'
  = f.input :description, label: '作品敘述'
  .form-actions
    = f.submit '送出', class: 'btn btn-primary btn-large'

app/views/admin/paintings/edit.html.slim
.span12
  .well.widget
    .widget-header
      h3.title 編輯作品
    = render 'form'

app/views/admin/paintings/index.html.slim
.row-fluid
  table.table.table-striped.table-bordered.table-condensed
    thead
      tr
        th 作品
        th 作者
        th 年份
        th 標籤
        th 建立時間
        th 更新時間
        th 操作
    tbody
      - @paintings.each do |painting|
        tr
          td= image_tag(painting.image.url(:thumb))
          td= link_to painting.author_name, admin_author_path(painting.author)
          td= painting.pub_year
          td
            - painting.tags.each do |tag|
              span.label.label-success.margin-right= tag.name
          td= l painting.created_at, format: :long
          td= l painting.updated_at, format: :long
          td
            .btn-group
              = link_to edit_admin_painting_path(painting), :class => 'btn' do
                = content_tag(:i, '', :class => 'icon icon-edit')
                '  編輯
              = link_to admin_painting_path(painting), method: :delete, data: { confirm: '確認要刪除嗎？' }, class: 'btn btn-danger' do
                = content_tag(:i, '', class: 'icon icon-remove')
                '  刪除
  = will_paginate @paintings

app/views/admin/paintings/new.html.slim
.span12
  .well.widget
    .widget-header
      h3.title 新增畫作
    = render 'form'

app/views/admin/paintings/show.html.slim
.row-fluid
  .span6
    .well.widget
      .widget-header
        h3 畫作
      .widget-content
        = image_tag(@painting.image.url)
  .span6
    .well.widget
      .widget-header
        h3 資訊
      .widget-content

app/views/authors/show.html.slim
.hero-unit
  .container
    h2= @author.name
.container.clearfix#main-content
  .row-fluid.portfolio-detail
    section.span12.project-description role="project-description"
      = image_tag @author.avatar_url(:normal), alt: @author.name, class: 'author-avatar'
      h6 簡介：
      p
        = markdown @author.description
    .span12.image-slider
      #carousel
        ul.my_slides
          - @author.paintings.each do |painting|
            li style="background-image: url(#{painting.image.url(:thumb)});"
              = link_to image_tag(asset_path("trans.gif")), painting_path(painting)

= content_for(:additional_js) do
  = javascript_include_tag 'fancybox_init'

app/views/feedbacks/create.js.erb
$(".submit-btn").prepend("<div class='alert alert-success'>感謝您的意見</div>");
$("#contact-form")[0].reset();

app/views/feedbacks/new.html.slim
.hero-unit
  .container
    h1 聯絡凱華
#main-content.container.clearfix
  .row-fluid.reverse-order.contact-page
    p.clearfix
      = "聯絡凱華"
    hr
    .span5
      p.right
        a.icon-map-marker.various href="#" &nbsp;
      p
        strong 聯絡資訊
        br
        | 台北市內湖區內湖路一段68號10樓
        br
        strong 電話:
        a.tele href="tel:+886-2-66038983" (02)6603-8983
        br
        strong 傳真:
        a.tele href="tel:+886-2-66038899" (02)6603-8899
        br
        strong email:
        a href="contact@startupo.cc" contact@startupo.cc
      /h3.short_headline.margin-top
        /span 接收電子報
      /p 輸入您的Email來隨時接收關於老師的消息
      /.input-append
        /input.span6 type="email" placeholder="Email" name="email"
        /button.btn.btn-primary 送出
    .span7
      = simple_form_for @feedback, remote: true, html: { id: 'contact-form', class: 'form-vertical', novalidate: 'novalidate' } do |f|
        fieldset
          = f.input :name, label: "姓名", input_html: { class: 'span10' }
          = f.input :phone, label: '電話', input_html: { class: 'span10' }
          = f.input :email, label: 'Email', input_html: { class: 'span10' }
          = f.input :message, label: '您的意見', input_html: { class: 'span10', rows: '3' }
          = f.submit '送出', class: 'btn btn-primary btn-large submit-btn'

app/views/layouts/admin.html.slim
doctype html
html lang="zh_tw"
  head
    title 凱華藝術投資管理後台
    = stylesheet_link_tag    "admin"
    = csrf_meta_tags
    meta name="viewport" content="width=device-width" initial-scale="1.0"
    meta charset="UTF-8"
    / [if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  body
    /!-- header
    #header.navbar
      .navbar-inner
        a.brand.hidden-phone href="/" 凱華藝術投資管理後台
    #left_layout
      /!-- main content
      #main_content.container-fluid
        /!-- page heading
        section.container-fluid
          .row-fluid
            - flash.each do |name, msg|
              div{class="alert alert-#{name == :notice ? "success" : "error"} fade in"}
                a.close data-dismiss="alert" &times;
                = simple_format(msg)
        .page-heading
          h2.page-title.muted
            i.icon-dashboard
            | 主控台
          .page-info.hidden-phone
        /!-- post wrapper
        .row-fluid
          = yield
      /!-- sidebar
      ul#sidebar.nav.nav-pills.nav-stacked
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.micon-picture
            span.hidden-phone 畫作
          ul.dropdown-menu
            li
              = link_to new_admin_painting_path do
                = content_tag(:i, '', class: 'micon-plus')
                ' 新增畫作
            li
              = link_to admin_paintings_path do
                = content_tag(:i, '', class: 'icon-list')
                ' 畫作列表
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.micon-user
            span.hidden-phone 作家
          ul.dropdown-menu
            li
              = link_to new_admin_author_path do
                = content_tag(:i, '', class: 'micon-plus')
                ' 新增作家
            li
              = link_to admin_authors_path do
                = content_tag(:i, '', class: 'icon-list')
                ' 作家列表
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.micon-broadcast
            span.hidden-phone 最新消息
          ul.dropdown-menu
            li
              = link_to new_admin_post_path do
                = content_tag(:i, '', class: 'micon-plus')
                ' 新增最新消息
            li
              = link_to admin_posts_path do
                = content_tag(:i, '', class: 'icon-list')
                ' 最新消息列表
        li
          = link_to admin_feedbacks_path do
            i.micon-mail
            span.hidden-phone 意見
    = javascript_include_tag "admin"

app/views/layouts/application.html.slim
| <!doctype html>
/![if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en" dir="ltr">
/![if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en" dir="ltr">
/![if IE 8] <html class="no-js lt-ie9" lang="en" dir="ltr">
/! [if gt IE 8]><!
html.no-js dir="ltr" lang="zh_tw"
  /! <![endif]
  head
    title 凱華藝術投資
    /! Meta Data ================
    meta charset="UTF-8"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    meta content="yes" name="apple-mobile-web-app-capable"
    /! CSS ================
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag 'modernizr.custom.87724'
    = csrf_meta_tags
  body.index
    /! begin accesibility skip to nav skip content
    ul.visuallyhidden#top
      li
        a href="#nav" title="Skip to navigation" accesskey="n" Skip to navigation
      li
        a href="#page" title="Skip to content" accesskey="c" Skip to content
    /! mobile navigation trigger
    h5.mobile_nav
      a href="javascript:void(0)"
        | &nbsp;
        span
    /! begin .header
    section.container.preheader
    header.header.clearfix
      .container
        /! begin #main_menu
        = render 'shared/main_menu'
        /! begin #logo
        #logo
          a href="/"
            /em Crisp Responsive HTML Retina Ready Bootstrap Goodness
            /! effing ie7 support
    /! begin #page - the container for everything but header
    #page
      = yield
      = render 'shared/footer'
      span.backToTop
        a href="#" 回到頁首
    = javascript_include_tag "application"
    = yield(:additional_js)

app/views/paintings/index.html.slim
#main-content.container.clearfix
  = will_paginate(@paintings, class: 'pagination-right no-margin pagination-mini')
  - @paintings.each_slice(4) do |a, b, c, d|
    .row-fluid
      ul.gallery
        li class="item #{a.tags.map(&:name)*" "}"
          = link_to painting_path(a), class: 'hover' do
            = image_tag(a.image.url(:usual))
            span.plus
          .entry-summary
            h4= a.name
            span.credit= link_to a.author_name, author_path(a.author)
        - if b
          li class="item #{b.tags.map(&:name)*" "}"
            = link_to painting_path(b), class: 'hover' do
              = image_tag(b.image.url(:usual))
              span.plus
            .entry-summary
              h4= b.name
              span.credit= link_to b.author_name, author_path(b.author)
        - if c
          li class="item #{c.tags.map(&:name)*" "}"
            = link_to painting_path(c), class: 'hover' do
              = image_tag(c.image.url(:usual))
              span.plus
            .entry-summary
              h4= c.name
              span.credit= link_to c.author_name, author_path(c.author)
        - if d
          li class="item #{d.tags.map(&:name)*" "}"
            = link_to painting_path(d), class: 'hover' do
              = image_tag(d.image.url(:usual))
              span.plus
            .entry-summary
              h4= d.name
              span.credit= link_to d.author_name, author_path(a.author)

  /.row-fluid
    /.filter-box.clearfix
      /span#filter
        /| 標籤
        /i.icon-sort
    /ul.gallery.four_col.clearfix.isotope
      /- @paintings.each do |painting|
        /li class="item #{painting.tags.map(&:name)*" "}"
          /= link_to painting_path(painting), class: 'hover' do
            /= image_tag(painting.image.url(:usual))
            /span.plus
          /.entry-summary
            /h4= painting.name
            /span.credit= link_to painting.author_name, author_path(painting.author)

  = will_paginate(@paintings, class: 'pagination-centered no-margin pagination-footer pagination-mini')

app/views/paintings/show.html.slim
.hero-unit
  .container
    h2= @painting.name
#main-content.container.clearfix
  .row-fluid.portfolio-detail
    .span12.image-slider
      = image_tag(@painting.image.url, class: 'painting', style: 'margin: 0 auto;')
    section.span12.project-description role="project-description"
      = simple_format @painting.description
      h6 年份：
      p
        = @painting.pub_year
      h6 標籤：
      p
        - @painting.tags.each do |tag|
          = link_to tag_path(tag.name) do
            = tag.name
            | ,
      h6 作者：
      p
        = link_to @painting.author_name, author_path(@painting.author)
    .row-fluid.related
      h3.span5 #{@painting.author_name}的其他作品：
      .span7
        ul
          - @painting.related_paintings.each do |painting|
            li style="background-image:url(#{painting.image.url(:thumb)})"
              a title="#{painting.name}" href="#{painting_path(painting)}"

app/views/posts/_sidebar.html.slim
section.span3.sidebar.secondary-column
  aside.widget
    h5.short_headline
      span 搜尋
    form.searchform
      input.span12 type="search" value="搜尋" onfocus="this.value=''" onblur="this.value='搜尋"
  aside.widget
    h5.short_headline
      span 最新文章
    .sidebar-tabs data-easytabs="true"
      .panels
        #tab-latest.active
          ul.blogposts.clearfix
            - @latest.each do |post|
              li
                span.date
                  span.month= l post.created_at, format: '%b'
                  span.day= l post.created_at, format: '%d'
                  span.year= l post.created_at, format: '%y'
                h3
                  = link_to post.title, post_path(post)
                = link_to truncate(post.content, length: 50)

app/views/posts/index.html.slim
.container.visible-phone.hidden-tablet.hidden-desktop
  p.right
    a.btn.btn-primary href="#secondary-nav"
      | 最新消息
      i.icon-align-justify
.hero-unit
  .container
    h2 最新消息
#main-content.container.clearfix
  .row-fluid.sidebar-right
    .span9.blog-summary.primary-column
      - @posts.each do |post|
        article.entry-post
          header.entry-header
            h3.entry-title
              = link_to post.title, post_path(post)
            .byline
              i.icon-time
              abbr.published title="#{post.created_at}"= l post.created_at, format: :short
              | &nbsp;&nbsp;
          .entry-content
            = simple_format truncate(post.content, length: 150)
            p.more.right
              = link_to '閱讀', post_path(post), class: 'btn btn-primary'
          footer.entry-footer
            span.blog.date
              span.month= l post.created_at, format: '%b'
              span.day= l post.created_at, format: '%d'
              span.year= l post.created_at, format: '%y'
      = will_paginate(@posts, class: 'pagination-right no-margin pagination-mini')
    = render 'sidebar'

app/views/posts/show.html.slim
.container.visible-phone.hidden-tablet.hidden-desktop
  p.right
    a.btn.btn-primary href="#secondary-nav"
      | 最新消息
      i.icon-align-justify
.hero-unit
  .container
    h2 最新消息
#main-content.container.clearfix
  .row-fluid.sidebar-right
    .span9.blog-summary.primary-column
      article.entry-post
        header.entry-header
          h3.entry-title
            = link_to @post.title, post_path(@post)
          .byline
            i.icon-time
            abbr.published title="#{@post.created_at}"= l @post.created_at, format: :short
            | &nbsp;&nbsp;
        .entry-content
          = simple_format @post.content
        footer.entry-footer
          span.blog.date
            span.month= l @post.created_at, format: '%b'
            span.day= l @post.created_at, format: '%d'
            span.year= l @post.created_at, format: '%y'
    = render 'sidebar'

app/views/shared/_footer.html.slim
#footer.clearfix
  .container
    .row-fluid
      .span6
        /section
          /h4 訂閱電子報
          /p 隨時接收來自凱華藝術投資的最新消息，我們不會任意散佈您的Email
          /form
            /.input-append
              /input.span6 type="email" placeholder="kate@startupo.cc" name="email"
              /button.btn.btn-primary 送出
        section
          h4 凱華藝術家
          ul.image-widget.clearfix
            - footer_authors.each do |author|
              li = link_to author_path(author) do
                  = image_tag(author.avatar.url(:thumb), alt: author.name)
                  p.author_link= author.name
        section
          h4 聯絡凱華
          p
            | 台北市內湖區新湖一路89號6樓
            br
            strong 電話：
            a.tele href="tel:+886227939776" (02)27939776
            br
            strong 傳真：
            | (02)2793-7657
            br
            strong email：
            a href="mailto:contact@knw.com.tw" contact@knw.com.tw
        section
          h4 最新消息
          ul.footerPosts
            - footer_posts.each do |post|
              li
                = link_to post.title, post_path(post)
                span.meta= l post.created_at, format: :long
      .span6
        section
          h4 追蹤我們
          = render 'shared/facebook'
          /ul.social
            /li
              /a.socicon.facebook href="https://www.facebook.com/KnwArt" data-original-title="Facebook"
  section.footerCredits
    .container
      ul.clearfix
        li ® 2012 凱華資源整合有限公司. All rights reserved.

app/views/shared/_main_menu.html.slim
nav#main_menu.ddsmoothmenu
  ul.accordmobile
    li= link_to '關於凱華', about_path
    li= link_to '作品集', paintings_path
    li= link_to '最新消息', posts_path
    li= link_to '聯絡凱華', new_feedback_path

app/views/welcome/about.html.slim
.hero-unit
  .container
    h2 關於凱華
#main-content.container.clearfix
  p 凱華創立於2013年4月。公司秉承誠信經營、專業服務的基本理念，致力於在藝術品投資管理服務。服務國內外文化藝術領域人士、收藏鑒賞家、企業界人士，致力於藝術品流通環節，整合各方優勢資源，傳播藝術的鑒賞、收藏、投資理念，營造集文化藝術的訊息交流、行銷交易和專業研討於一體的文化藝術平台。
  p 不定期舉辦藝術鑑賞會、藝術家私密聚會、藝術投資講座等。持續挖掘最俱投資價值的藝術品推薦給所有客戶。
  h3 凱華服務項目：
  ol
    li 藝術經紀。
    li 藝術品銷售。
    li 藝術品委託。
    li 提供客戶藝術投資與金融整合性服務產品。
    li 各類藝術市場財富管理。
    li 藝術品投資顧問。

app/views/welcome/index.html.slim
.lemmon-wrap.clearfix
  #lemmon-slider.lemmon-slider
    ul
      - @paintings.each do |painting|
        li
          = link_to image_tag(painting.image.url(:for_index), alt: ""), painting_path(painting)
          .summary
            = link_to painting_path(painting) do
              h3= painting.name
              p= painting.author_name
  .controls
    a.prev-page href="#" 上一頁
    a.next-page href="#" 下一頁